spring-statemachine-core/src/main/java/org/springframework/statemachine/StateMachine.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineConfiguration.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineFactoryConfiguration.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/region/Region.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractSimpleState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/EnumState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/RegionState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/State.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/StateMachineState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/Transition.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineFactoryTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/guard/GuardTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/guard/SpelExpressionGuardTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/listener/ListenerTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/InitialStateTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/RegionStateTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/SubmachineStateTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/transition/TransitionTests.java

- resolves issues #2 and #4
- refactor states so that we can use submachines
and regions to compose a state.
- refactor some concepts around StateMachine now that
it extends Region.

Base support for submachines and regions

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/EnumStateMachine.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineStateBuilder.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineStates.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/StateConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/region/Region.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/EnumStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/config/ConfigurationTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/EndStateTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/RegionStateTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/SubmachineStateTests.java

Add base support for end/final state

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/event/AbstractStateMachineEvent.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/event/DefaultStateMachineEventPublisher.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/event/LoggingListener.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/event/OnStateChangedEvent.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/event/StateMachineEventPublisher.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/event/StateMachineEventPublisherConfiguration.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/LifecycleObjectSupport.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineContextUtils.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/event/StateMachineEventTests.java

- tidy up how listener event is sent together
with app context events.
- resolves #12

Add base support for app context event

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/StateMachineState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/SubStateMachineTests.java

- Fixes #23
- Transition with submachine now exists and enters
super state if transition is external.

Fix state handling with substates

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/StateData.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitionBuilder.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitions.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/ChoiceTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultChoiceTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/StateConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractSimpleState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ChoicePseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/DefaultPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/EnumState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/PseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/PseudoStateKind.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/RegionState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/State.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/StateMachineState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/EnumStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/RegionMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/SubStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/ChoiceStateTests.java

- Adding choice pseudostate with first/then/last
structure which is a synonym for if/elseif/else.
- This is a first attempt to bring better pseudostate
model to a framework.
- Fixes #41

Support choice pseudostate

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/RegionState.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/RegionMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/RegionStateTests.java

- Further fixes for this issue
- Fix some tests which really test wrong conditions.
- Disabled one test which is more feasible to
fix with region fork/join #39
- Fixes #54 again

RegionState not created with nested states - take 2

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitionBuilder.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitions.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultForkTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultJoinTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/ForkTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/JoinTransitionConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/StateConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ChoicePseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/CompositePseudoStateListener.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/DefaultPseudoStateContext.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ForkPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/HistoryPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/JoinPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/PseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/PseudoStateContext.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/PseudoStateListener.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/RegionState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineObjectSupport.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/RegionMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/ForkStateTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/JoinStateTests.java
spring-statemachine-core/src/test/resources/log4j.properties

- Adding first changes for supporting fork and join
concepts with regions.
- Change of some pseudostate concepts to have
better model for this and future work.
- Fixes #39

Support fork/join with regions

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnableStateMachine.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnableStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineCommonConfiguration.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineConfigurationImportSelector.java
spring-statemachine-samples/src/main/java/demo/CommonConfiguration.java

- Add StateMachineCommonConfiguration for task
executing and scheduling.
- Add StateMachineConfigurationImportSelector for
context event configuration.
- Fixes #40

Tune automatic configuration

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/EndStateTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/transition/TransitionTests.java

- Add better support for triggerless transitions in regions.
- Change concept how triggerless transitions are handled.
- Fixes #63

Fix triggerless transition in regions

---

README.adoc

Fix typos and phrasing where appropriate.

Refine README

---

docs/src/reference/asciidoc/preface.adoc

As I am reading the docs, also trying to help spotting typos.
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

Fixed some typos in reference guide preface.

---

docs/src/reference/asciidoc/introduction.adoc

Fixed some typos and very minor edits.
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

Typos and some minor fixes in reference guide introduction.

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ObjectState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/RegionState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/StateMachineState.java

- Fix to create empty collections in
favour of returning nulls.
- Fixes #271

No null collections from AbstractState

---

gradle.properties
settings.gradle
spring-statemachine-data/build.gradle
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbActionRepository.java
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbGuardRepository.java
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryAction.java
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryGuard.java
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryState.java
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryTransition.java
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbStateRepository.java
spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbTransitionRepository.java
spring-statemachine-data/mongodb/src/test/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryTests.java
spring-statemachine-data/mongodb/src/test/java/org/springframework/statemachine/data/mongodb/MongoDbRule.java
spring-statemachine-data/mongodb/src/test/resources/data10.json
spring-statemachine-data/mongodb/src/test/resources/data11.json
spring-statemachine-data/mongodb/src/test/resources/data12.json
spring-statemachine-data/mongodb/src/test/resources/data13.json
spring-statemachine-data/mongodb/src/test/resources/data2.json
spring-statemachine-data/mongodb/src/test/resources/data3.json
spring-statemachine-data/mongodb/src/test/resources/data4.json
spring-statemachine-data/mongodb/src/test/resources/data5.json
spring-statemachine-data/mongodb/src/test/resources/data6.json
spring-statemachine-data/mongodb/src/test/resources/data7.json
spring-statemachine-data/mongodb/src/test/resources/data8.json
spring-statemachine-data/mongodb/src/test/resources/data9.json

- Pretty much following what was done
for jpa and redis.
- Fixes #275

Add mongodb repository config support

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineFactoryTests.java

- Factory now listens machine event if autostart
is requested which should give fully started machine
i.e. if asynch executor is used. Bails out after 30
seconds. Further tweaks like allowing user to define
this time or conditionally not wait could be added later.
- Fix typos.
- Fixes #298

Make autostart smarter

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java

- Polish to do checks for debug/trace logs
- Fixes #329

Prevent debug calls

---

spring-statemachine-build-tests/src/test/java/org/springframework/statemachine/buildtests/TimerSmokeTests.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/action/ActionAndTimerTests.java

- Change how some internals in
AbstractStateMachine are synchronized
to limit changes for deadlock.
- Relates #359

Add additinal sync

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineSmokeTests.java
spring-statemachine-samples/persist/src/test/java/demo/persist/PersistTests.java

- Removing some sync blocks which imho
are not needed anymore.
- Adding some smoke tests.
- Relates to #364

Fix possible deadlock

---

spring-statemachine-core/src/test/java/org/springframework/statemachine/EventDeferTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/monitor/StateMachineMonitorTests.java

- Relates to #343
- Relates to #376

Backport ci test changes from master

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractStateMachinePersister.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/persist/DefaultStateMachinePersisterTests.java

- Fix AbstractStateMachinePersister to handle
recursive machines and regions.
- Fixes #391

Add recursive context build

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/action/Actions.java

Fixed typing mistake in the method description

Fix method description typo

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/service/DefaultStateMachineService.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/service/StateMachineService.java
spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/StateMachineConfig.java
spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/StateMachineController.java

- First take on new interface StateMachineService with
its default impl.
- Modify datajpapersist sample to use it.

Add base DefaultStateMachineService implementation

---

spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/StateMachineController.java

- Fix sample per changed release logic
in DefaultStateMachineService.

Fix datajpapersist sample

---

spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryState.java

- Define fk in @CollectionTable instead trying
to wrongly use @JoinTable
- Fixes #468

Change JPA deferred events constraint

---

docs/src/reference/asciidoc/sm.adoc
docs/src/reference/asciidoc/whatsnew.adoc

- Add more info into what's new in 1.2.8
- Small polish
- Relates to #476

Polish docs

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/state/EndStateTests.java

- Remove extra logging
- Polish tests, remove thread sleeps
- Relates #466

Polish tests and executor

---

docs/src/reference/asciidoc/sm.adoc
spring-statemachine-core/src/main/java/org/springframework/statemachine/StateMachineMessageHeaders.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/action/StateDoActionPolicy.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/ObjectStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineConfigurationBuilder.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/ConfigurationConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultConfigurationConfigurer.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/ConfigurationData.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineUtils.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/action/StateDoActivityActionTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests11.java

- Add new concepts around executing state do actions
allowing to use timeouts via StateDoActionPolicy.
- Global config per machine or via event headers.
- Fixes #501

Support executing state action with timeout

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/trigger/TimerTrigger.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/trigger/TimerTriggerTests.java

Add getters on some fields in TimeTrigger #533

Add getters on some fields in TimeTrigger #533

---

docs/src/reference/asciidoc/sm.adoc

fix wording: must be used +{in} order to

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/support/ReactiveStateMachineExecutor.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/EventDeferTests.java

- In ReactiveStateMachineExecutor deferList is clear
with deferred event if it triggers.
- Fixes #747

Clear event defer list

---

build.gradle
spring-statemachine-recipes/src/test/java/org/springframework/statemachine/recipes/TasksHandlerTests.java
spring-statemachine-uml/src/test/java/org/springframework/statemachine/uml/UmlStateMachineModelFactoryTests.java

Reactive test changes for uml and recipes

---

build.gradle
spring-statemachine-data/build.gradle
spring-statemachine-data/jpa/src/test/java/org/springframework/statemachine/data/jpa/JpaRepositoryTests.java
spring-statemachine-data/mongodb/src/test/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryTests.java
spring-statemachine-data/redis/src/test/java/org/springframework/statemachine/data/redis/RedisRepositoryTests.java

Reactive test changes for data

---

build.gradle
spring-statemachine-data/build.gradle
spring-statemachine-samples/build.gradle
spring-statemachine-samples/cdplayer/src/test/java/demo/cdplayer/CdPlayerTests.java
spring-statemachine-samples/persist/src/test/java/demo/persist/PersistTests.java
spring-statemachine-samples/showcase/src/test/java/demo/showcase/ShowcaseTests.java
spring-statemachine-samples/tasks/src/test/java/demo/tasks/TasksTests.java
spring-statemachine-samples/turnstile/src/test/java/demo/turnstile/TurnstileTests.java
spring-statemachine-samples/washer/src/test/java/demo/washer/WasherTests.java

Reactive test changes for samples

---

spring-statemachine-samples/cdplayer/src/main/java/demo/cdplayer/Application.java
spring-statemachine-samples/cdplayer/src/main/java/demo/cdplayer/CdPlayer.java
spring-statemachine-samples/cdplayer/src/main/java/demo/cdplayer/StateMachineCommands.java
spring-statemachine-samples/datajpa/src/main/java/demo/datajpa/StateMachineController.java
spring-statemachine-samples/datajpamultipersist/src/main/java/demo/datajpamultipersist/StateMachineController.java
spring-statemachine-samples/datapersist/src/main/java/demo/datapersist/StateMachineController.java
spring-statemachine-samples/deploy/src/main/java/demo/deploy/StateMachineController.java
spring-statemachine-samples/eventservice/src/main/java/demo/eventservice/StateMachineController.java
spring-statemachine-samples/monitoring/src/main/java/demo/monitoring/StateMachineController.java
spring-statemachine-samples/ordershipping/src/main/java/demo/ordershipping/StateMachineController.java
spring-statemachine-samples/persist/src/main/java/demo/persist/StateMachineCommands.java
spring-statemachine-samples/scope/src/main/java/demo/scope/StateMachineController.java
spring-statemachine-samples/security/src/main/java/demo/security/StateMachineController.java
spring-statemachine-samples/showcase/src/main/java/demo/showcase/StateMachineCommands.java
spring-statemachine-samples/src/main/java/demo/AbstractStateMachineCommands.java
spring-statemachine-samples/tasks/src/main/java/demo/tasks/Application.java
spring-statemachine-samples/tasks/src/main/java/demo/tasks/StateMachineCommands.java
spring-statemachine-samples/tasks/src/main/java/demo/tasks/Tasks.java
spring-statemachine-samples/turnstile/src/main/java/demo/turnstile/StateMachineCommands.java
spring-statemachine-samples/washer/src/main/java/demo/washer/StateMachineCommands.java
spring-statemachine-samples/web/src/main/java/demo/web/StateMachineController.java
spring-statemachine-samples/zookeeper/src/main/java/demo/zookeeper/StateMachineCommands.java

Reactive changes for samples

---

spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests10.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests11.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests2.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests5.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests6.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/IntroSample.java

Reactive changes for docs

---

spring-statemachine-core/src/test/java/org/springframework/statemachine/RelayTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/StateContextTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/config/SessionScopedAnnotationTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/config/SessionScopedManualTests.java
spring-statemachine-core/src/test/java/org/springframework/statemachine/monitor/StateMachineMonitorTests.java

Reactive test changes for core

---

build.gradle

Update the version of spring-doc-resources and the highlighter for HTML
to get the latest look and feel and nicer code listings.

Update spring-doc-resources version and highlight

---

spring-statemachine-build-tests/src/test/java/org/springframework/statemachine/buildtests/ForkJoinEntryExitTests.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/action/Actions.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ChoicePseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/EntryPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ExitPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ForkPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/HistoryPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/JoinPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/JunctionPseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/state/PseudoState.java
spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java

- Change entry/exit functions to reactive types
to have those in a reactive stack.
- Fixes #878

Reactive PseudoStates

---

spring-statemachine-samples/deploy/src/main/java/demo/deploy/StateMachineConfig.java
spring-statemachine-samples/deploy/src/main/resources/model.notation
spring-statemachine-samples/deploy/src/main/resources/model.uml

spring-statemachine-samples-deploy -> StateMachineConfig misprints

minor syntax fix

---

spring-statemachine-core/src/main/java/org/springframework/statemachine/support/ReactiveStateMachineExecutor.java

- Change to use reactive method for lifecycle handling
for triggers in an executor.

Use reactive lifecycle for triggers

---

spring-statemachine-uml/src/main/java/org/springframework/statemachine/uml/support/UmlUtils.java
spring-statemachine-uml/src/test/java/org/springframework/statemachine/uml/UmlStateMachineModelFactoryTests.java
spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/transition-effect-spel.di
spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/transition-effect-spel.notation
spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/transition-effect-spel.uml

- Add missing resolve/create for action if type is defined as spel.
- Fixes #889

Missing spel effect with transition in uml

---

build.gradle

Update boot 2.4.3

---

spring-statemachine-data/src/main/java/org/springframework/statemachine/data/RepositoryStateMachineModelFactory.java

Fix repository factory choice junction action construction

---

spring-statemachine-samples/datapersist/src/main/java/demo/datapersist/StateMachineConfig.java

fix variable name
