- spring-statemachine-core/src/main/java/org/springframework/statemachine/StateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/region/Region.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/RegionState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/State.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/RegionMachineTests.java
- refactor event processing around state
interfaces order to pass event from a state
machine into a regions.
> Events not send to regions

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/StateConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/HistoryPseudoState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/PseudoStateKind.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/StateMachineState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/HistoryStateTests.java
- Fixes #50 bug which were revealed by
trying to use history state concepts.
- Fixes #38 for history features.
- Base functionality for deep and shallow
histories.
- Some housekeeping and polish before doing
more system wide spring cleaning.
> Support history pseudostates

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnumStateMachineFactory.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/RegionMachineTests.java
- EnumStateMachineFactory didn't add created machine
which wrapped region states into a internal
machine map which is used to resolve built machines.
- Adding test which simply tests nested regions.
- Fixes #54
> RegionState not created with nested states

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/StateData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurer.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurerTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/InitialStateTests.java
- Tweak DefaultStateConfigurer so that we don't need
to define initial state as additional state. Also
fixed some other issue which caused a bit of a mess
when i.e multiple states were introduces twice.
- Fixes #29
> Should not define initial state as state

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/LifecycleObjectSupport.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/transition/TransitionTests.java
- Fix correct handling in this case.
- Tune lifecycle so that recursive calls to
start() in a same thread doesn't cause multiple
calls to doStart().
> Triggerless transition doesn't work from initial to terminate

- docs/src/reference/asciidoc/sm.adoc
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnableStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnableStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/EnableWithStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/processor/StateMachineHandlerCallHelper.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineObjectSupport.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/annotation/MethodAnnotationWithBuilderTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/annotation/MethodAnnotationWithFactoryTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests4.java
- Add support so that @WithStateMachine can be used with
machines build via @EnableStateMachineFactory or via
manual builders.
- Adding new annotation @EnableWithStateMachine to help
handling needed context configuration.
- Add tests and docs.
- Fixes #292
- Fixes #224
> @WithStateMachine with factory and builder

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineConfiguration.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineFactoryConfiguration.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/MachineTypedTests.java
- Modify StateMachineConfiguration and StateMachineFactoryConfiguration
so that if you have different states and events classes with multiple
machines or factories, you can autowire by types without
adding qualifiers.
- Manually try to discover generic types from enclosing adapther class
and if succesfull pass that information into bean definition
as ResolvableType.
- Fixes #306
> Better generics handling with adapters

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/DefaultStateMachineExecutorTests.java
- Add new tests for DefaultStateMachineExecutor to find
possible causes for a deadlock.
- Handle lifecycle scenario little differently
if timer is fired during a executor starting phase
order to not getting into a deadlock.
- Relates to #315
> Timer trigger deadlock in DefaultStateMachineExecutor

- docs/src/reference/asciidoc/sm.adoc
- spring-statemachine-uml/src/main/java/org/springframework/statemachine/uml/support/UmlModelParser.java
- spring-statemachine-uml/src/test/java/org/springframework/statemachine/uml/UmlStateMachineModelFactoryTests.java
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/simple-connectionpointref.di
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/simple-connectionpointref.notation
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/simple-connectionpointref.uml
- Add support to uml parser to properly
detect and use exit/entry points if those
are used via connection ref points with
submachine references.
- Fixes #323
> Support Connection Point References

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/InitialTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/Transition.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/StateContextTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateContextExpressionMethodsTests.java
- Add new api to Transition to expose calling
its actions.
- Modify rest of a framework to first notify before
calling transtion action.
- Fixes #322
> Notify transition before calling its actions

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/trigger/CleanTimerTests.java
- Trying to handle scenario where TimerTrigger keeps firing
even if machine is stopped or has moved away from its
hosting state.
- Explicitely handle trigger starts/stops in
DefaultStateMachineExecutor when executor itself
is started/stopped.
- Fixes #321
> Disarm timers

- build.gradle
- spring-statemachine-build-tests/src/test/java/org/springframework/statemachine/buildtests/AbstractBuildTests.java
- spring-statemachine-build-tests/src/test/java/org/springframework/statemachine/buildtests/RedisPersistTests.java
- spring-statemachine-kryo/src/main/java/org/springframework/statemachine/kryo/StateMachineContextSerializer.java
- Add missing serialisation for history map and machine id
- Fix possible NPE with extended state
- Fixes #331
- Fixes #333
> StateMachineContextSerializer handles history and id

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/action/ActionErrorTests.java
- Executor is following anonymous transitions in a loop
and if there is an exception in actions with this transition,
effectively executor ended into infinite loop.
- No bailing out from this loop if we cannot continue.
- Fixes #344
> Fix action error in anonymous transition

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateChangeInterceptorTests.java
- Now calling post state interceptor with
correct/same state as pre.
- Fixes #353
> Fix post interceptor call

- docs/src/reference/asciidoc/sm.adoc
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/ChoiceTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultChoiceTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultJunctionTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/JunctionTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/ChoiceData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/JunctionData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ChoicePseudoState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/JunctionPseudoState.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/ChoiceStateTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/JunctionStateTests.java
- spring-statemachine-uml/src/main/java/org/springframework/statemachine/uml/support/UmlModelParser.java
- spring-statemachine-uml/src/test/java/org/springframework/statemachine/uml/UmlStateMachineModelFactoryTests.java
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/action-with-transition-choice.di
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/action-with-transition-choice.notation
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/action-with-transition-choice.uml
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/action-with-transition-junction.di
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/action-with-transition-junction.notation
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/action-with-transition-junction.uml
- Adding support for javaconfig/uml to define
actions for transitions leading out from a
choice or junction states.
- Support for action for incoming transition is
already implemented as it is defined as normal
transition.
- Fixes #108
> Support actions with transition via choice/junction pseudostate

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateChangeInterceptorTests.java
This PR fixes issue #367 where PreStateChange interceptors for END states are called twice.
> Fix PreStateChange interceptors being called twice for END states (#367)

- spring-statemachine-core/src/main/java/org/springframework/statemachine/processor/StateMachineHandlerCallHelper.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/annotation/MethodAnnotationTests.java
- Change processor registration so that if @WithStateMachine is
used with 'id', 'name' is skipped because it defaults to 'stateMachine'
and would cause extra registration.
- Fixes #370
> @WithStateMachine may register too many processors

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/StateConfigurer.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/ConfigurationTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/EndStateTests.java
- Add missing support for defining more than one
end states and as it's just missing from javaconfig.
- Fixes #368
> Add support for multiple end states with javaconfig

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- Taking local copy of current state
to prevent npe without sync block.
- Relates to #364
> Prevent npe on accept

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/persist/StateMachinePersistTests.java
- Now calling post state interceptors at end
of state change which gives machine a change
to stop if state is terminal.
- Fixes #379
> Fix terminal state for persist

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineUtils.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/annotation/MethodAnnotationTests.java
- Fix case where method was annotated with
@OnExtendedStateChanged(key = "V1"), V1 was
changed which didn't result call to that method.
- Fixes #387
> Fix OnExtendedStateChanged with key

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/persist/StateMachinePersistTests.java
- Fixing machine lifecycle logic when machine
is restored which effectively should not touch
any lifecycle methods as start/stop is
user level action.
- Remove start/stop from restore and attempt to
do same when root machine is started. This also
needed some further changes as some functionality
for restore was essentially broken
- Fixes #386
> Change machine lifecycle with restore

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/persist/StateMachinePersistTests3.java
- Resetting a machine with null context currently
just resets to initial state and clear extended
state variables. Enhance also to clear machine id
which as a user level variable may cause some other
trouble. There are no internal functionality for this
id as it's meant for user consumption.
- Fixes #390
> Clean machine id when restored with null context

- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineResetTests.java
- As passing in null context don't have any
meaning other than doing reset with pre-defined
behaviour which currently just resets back to
initial state and clears extended state variables.
Now Also clearing machine id back to null which is
anyway a default value.
- Fixes #381
> Clear machine id with null context restore

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
Hello,
Error during execution of `Action` during (internal or external) transition was not fully logged.
```java
Builder<String, String> builder = StateMachineBuilder.builder();
builder
.configureConfiguration()
.withConfiguration()
.beanFactory(beanFactory)
.autoStartup(true);
builder
.configureStates()
.withStates()
.initial("a")
.states(new HashSet<>(asList("a", "b")));
builder
.configureTransitions()
.withInternal()
.source("a")
.event("int")
.action(c -> { throw new RuntimeException("oups"); })
.and()
.withExternal()
.source("a")
.event("ext")
.action(c -> { throw new RuntimeException("oups"); })
.target("b");
StateMachine<String, String> stateMachine = builder.build();
stateMachine.sendEvent("int");
stateMachine.sendEvent("ext");
```
Original logging:
```
2017-09-17 19:18:24.331 …
```
> Fix logging message when transition action throws exception

- spring-statemachine-core/src/main/java/org/springframework/statemachine/processor/StateMachineHandlerCallHelper.java
- Makes things less chatty if BeanFactory is null in
StateMachineHandlerCallHelper as this is usually a case
with manual builders outside of app context.
- Fixes #412
> Handle null BeanFactory in StateMachineHandlerCallHelper

- build.gradle
- settings.gradle
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineConfigurationBuilder.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineConfigurationConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultPersistenceConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/PersistenceConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/ConfigurationData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractPersistingStateMachineInterceptor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/StateMachineRuntimePersister.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/model/StateMachineModelTests.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaPersistingStateMachineInterceptor.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryStateMachine.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryStateMachinePersist.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaStateMachineRepository.java
- spring-statemachine-data/jpa/src/test/java/org/springframework/statemachine/data/jpa/JpaRepositoryTests.java
- spring-statemachine-data/src/main/java/org/springframework/statemachine/data/RepositoryStateMachine.java
- spring-statemachine-data/src/main/java/org/springframework/statemachine/data/RepositoryStateMachineModelFactory.java
- spring-statemachine-data/src/main/java/org/springframework/statemachine/data/RepositoryStateMachinePersist.java
- spring-statemachine-data/src/main/java/org/springframework/statemachine/data/StateMachineRepository.java
- spring-statemachine-kryo/src/main/java/org/springframework/statemachine/kryo/KryoSerialisationService.java
- spring-statemachine-samples/build.gradle
- spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/Application.java
- spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/StateMachineConfig.java
- spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/StateMachineController.java
- spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/StateMachineLogListener.java
- spring-statemachine-samples/datajpapersist/src/main/resources/application.yml
- spring-statemachine-samples/datajpapersist/src/main/resources/templates/states.html
- spring-statemachine-samples/datajpapersist/src/test/java/demo/datajpapersist/DataJpaPersistTests.java
- Add new repository model for storing StateMachineContext
via a new StateMachineRepository.
- New StateMachineRuntimePersister interface to abstract needed
functionality to do a runtime machine persistence.
- As runtime persistence, as of now, is done via interceptors, define
JpaRepositoryStateMachinePersist and JpaPersistingStateMachineInterceptor
to define StateMachineRuntimePersister logic.
- Add new datajpapersist sample demonstrating new concepts.
- Keep tests related to jpa as there's not redis/mongo integration
implemented in this first iteration.
- As this is going to be WIP until features around this issues
are completed, docs, etc are not yet added. Also, interfaces and impls
are subject to change during a process.
- Relates to #423
- Relates to #426
- Relates to #427
> Preliminary support for Spring Data persist

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineConfigurationBuilder.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultPersistenceConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/PersistenceConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractPersistingStateMachineInterceptor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/StateMachineRuntimePersister.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/service/DefaultStateMachineService.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaPersistingStateMachineInterceptor.java
- spring-statemachine-data/jpa/src/test/java/org/springframework/statemachine/data/jpa/JpaRepositoryTests.java
- spring-statemachine-samples/datajpapersist/src/main/java/demo/datajpapersist/StateMachineConfig.java
- Fix wrong acquire logic in DefaultStatemachineService.
- Overhaul StateMachineRuntimePersister
- Change StateMachineRuntimePersister to extend
StateMachinePersist which should work better on
a bean level. Also add generic type T to it and
config where needed.
- Relates to #427
> Change persistence model structure

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineExecutor.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/EventHeaderTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/transition/TransitionTests.java
- In AbstractStateMachine and DefaultStateMachineExecutor
do a little more synchronisation so that submachine is allowed
to do its run-to-completion before parent machine can do its
own transitions. This should fix use cases, when submachine
starts, does its transitions and actions, parent wont try to
do its own triggerless transtions.
- Adding some new tests and fixing one other sync issue with end state.
- Relates to #442
> Fix threading issues

- spring-statemachine-core/src/main/java/org/springframework/statemachine/service/DefaultStateMachineService.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/service/StateMachineService.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/service/DefaultStateMachineServiceTests.java
- Add new interface methods to StateMachineService to ease
starting and stopping when acquiring or releasing machines.
> Add start/stop feature to DefaultStateMachineService

- spring-statemachine-core/src/main/java/org/springframework/statemachine/service/DefaultStateMachineService.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/service/DefaultStateMachineServiceTests.java
- Now implementing DisposableBean and clearing/stopping
machines if service is destroyed.
> Add stop logic to DefaultStateMachineService

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineResetTests.java
- Instead of changing extended state object, use existing one
by clearing it and setting new values from context.
- Fixes #447
> Fix extended state handling during reset

- spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbPersistingStateMachineInterceptor.java
- spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryStateMachine.java
- spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryStateMachinePersist.java
- spring-statemachine-data/mongodb/src/main/java/org/springframework/statemachine/data/mongodb/MongoDbStateMachineRepository.java
- spring-statemachine-data/mongodb/src/test/java/org/springframework/statemachine/data/mongodb/MongoDbRepositoryTests.java
- spring-statemachine-data/redis/src/main/java/org/springframework/statemachine/data/redis/RedisPersistingStateMachineInterceptor.java
- spring-statemachine-data/redis/src/main/java/org/springframework/statemachine/data/redis/RedisRepositoryStateMachine.java
- spring-statemachine-data/redis/src/main/java/org/springframework/statemachine/data/redis/RedisRepositoryStateMachinePersist.java
- spring-statemachine-data/redis/src/main/java/org/springframework/statemachine/data/redis/RedisStateMachineRepository.java
- spring-statemachine-data/redis/src/test/java/org/springframework/statemachine/data/redis/RedisRepositoryTests.java
- Add similar implementations as done for JPA
which uses redis and mongo.
- Relates #428
> Add redis/mongo for machine persistence

- spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractPersistingStateMachineInterceptor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/Function.java
- Now in AbstractPersistingStateMachineInterceptor it is possible
to use a Function to define which variables are persisted. This
is for cases where it is not desirable to persist some variables
for variours reasons.
- Relates to #423
> Allow to define extended state variables during persist

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineConfiguration.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineFactoryConfiguration.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/MachineTypedTests.java
- Naively with StateMachineConfigurerAdapter or EnumStateMachineConfigurerAdapter
only immediate super type were checked to find user level generics to
instruct IOC for proper resolvable types. This worked with almost all cases
except if user created new base type out from StateMachineConfigurerAdapter and
bean id didn't match what what was trying to get autowired if multiple adapters
were in use.
- Correctly find resolvable type as StateMachineConfigurerAdapter in ResolvableType
which finds an exact correct type to get generics.
- Fixes #454
> Find correct super type generics for configurer adapter

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/ObjectStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineConfigurationBuilder.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/ConfigurationConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultConfigurationConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/ConfigurationData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/TransitionComparator.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/TransitionConflightPolicy.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/DefaultStateMachineExecutorTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/TransitionComparatorTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/transition/TransitionOrderTests.java
- Add new TransitionConflightPolicy and allow to configure
it via an adapter interfaces.
- For now, use it in TransitionComparator which sorts transitions
based on source states. This gives PARENT and CHILD sorting
and allows to choose conflicting transitions either from parent
or child.
- Add new sync thread used in submachines so that one thread is used
in a whole call stach per machine(regions still get their own as well
as a root machine).
- Fixes #456
> Conflicting transitions cause undefined order behaviour

- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/model/StateMachineModelFactoryTests.java
- While original issue is already fixed in 1.2.x, adding
specific tests for checking if config is coming from model
or adapter.
- Fixes #459
> Add configuration tests for StateMachineModelFactory

- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryAction.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryGuard.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryState.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryStateMachine.java
- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryTransition.java
- Modify existing JPA entity classes to
have a fixed names for constraints and
foreign key. Also name used tables so that
we don't get crazy long names which are
causing issues with some DB's
- Fixes #468
- Fixes #469
> JPA entity changes

- spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryState.java
- Change initial field to initialState which
resolves initial reserved keywork problem.
- Fixes #472
> Change JPA initial state field

- spring-statemachine-uml/src/main/java/org/springframework/statemachine/uml/support/UmlModelParser.java
- spring-statemachine-uml/src/test/java/org/springframework/statemachine/uml/UmlStateMachineModelFactoryTests.java
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/simple-actions.notation
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/simple-actions.uml
- UmlModelParser wrongly set spel based state action as
exit action. Change this to behave same as bean based
action is used.
- Fixes #474
> Fix uml spel state action

- docs/src/reference/asciidoc/sm.adoc
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/ObjectStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineConfigurationBuilder.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/ConfigurationConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultConfigurationConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/ConfigurationData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/TransitionComparator.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/TransitionConflictPolicy.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/TransitionComparatorTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/transition/TransitionOrderTests.java
- Changing unfortunate typo conflight vs. conflict.
- Also add some docs for transition conflict.
- Relates to #456
- Relates to #476
> Fix typo in transition conflict

- docs/src/reference/asciidoc/sm.adoc
- spring-statemachine-test/src/main/java/org/springframework/statemachine/test/StateMachineTestPlan.java
- spring-statemachine-test/src/main/java/org/springframework/statemachine/test/StateMachineTestPlanBuilder.java
- spring-statemachine-test/src/test/java/org/springframework/statemachine/test/StateMachineTestingTests.java
- spring-statemachine-test/src/test/java/org/springframework/statemachine/test/docs/DocsTestSampleTests.java
- For testing extended state variables, it's now possible to use
new method expectVariableMatcher which takes hamcrest matcher
as an argument.
- Fixes #483
> Add hamcrest integration to variables in StateMachineTestPlanBuilder

- spring-statemachine-build-tests/src/test/java/org/springframework/statemachine/buildtests/LinkedRegionsTests.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/listener/OrderedComposite.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/JoinPseudoState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ObjectState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/RegionState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/StateListener.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/StateListenerAdapter.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/LifecycleObjectSupport.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/Transition.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/CompletionEventTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/EndStateTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/state/JoinStateTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateContextExpressionMethodsTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/transition/TransitionTests.java
- spring-statemachine-samples/tasks/src/test/java/demo/tasks/TasksTests.java
- spring-statemachine-samples/tasks/src/test/resources/logback.xml
- Currently into as internal new feature, add state
completed concecept and use it in various places.
- Main focus for this commit is to add support using
anonymous transitions with state do actions which
requires proper completion schematics.
- Internal functionality here will probably expose to
user level in future releases using various other
concepts.
- Fixes #466
> Add support for completion transitions

- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/State.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/AbstractStateMachineTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurerTests.java
State has getters for entry and exit actions but no getter for state actions.
- Add State::getStateActions() in State
- Implement in AbstractState
- Update tests
https://github.com/spring-projects/spring-statemachine/issues/502
> Add getter for state actions

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- Change executor behaviour so that it consumes all queued triggers
which should help for cases where timers queue triggers where
processing is waiting transition to happen.
- Fixes #538
> Executor may build up triggers with timers

- build.gradle
- gradle.properties
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/DefaultStateMachineExecutor.java
- Add proper build sniffer config to catch
jdk7 compat. This is pretty much one used
in a framework build itself.
- Fix jdk7 usage in DefaultStateMachineExecutor.
- Resolves #561
> Fix 1.2.x build for jdk7

- docs/src/reference/asciidoc/appendix.adoc
The reference docs have the word `numbad` in section B.3.8.
This PR changes it to numpad, which I believe is the intended word.
> Fix numpad typo in Reference documentation, section B.3.8

- spring-statemachine-uml/src/main/java/org/springframework/statemachine/uml/support/UmlModelParser.java
- spring-statemachine-uml/src/test/java/org/springframework/statemachine/uml/UmlStateMachineModelFactoryTests.java
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/pseudostate-in-submachine.di
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/pseudostate-in-submachine.notation
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/pseudostate-in-submachine.uml
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/pseudostate-in-submachineref.di
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/pseudostate-in-submachineref.notation
- spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/pseudostate-in-submachineref.uml
- In a case where uml is drawn with submachine references where
a pseudostate like choice is defined in a reference, UmlModelParser
needs to find possible parent by following machine/state references
to match a state name which references to a this particular machine.
- Actual bug was because pseudostate parent wasn't found it became null,
thus causing it to be defined in a root machine which then caused
other cascading errors like nasty loop shown in #729.
- Fixes #729
> Fix pseudostate parent with uml machine references

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateChangeInterceptorTests.java
- This is fixing some issues where anonymous transitions
are causing post state call to happen too early i.e.
with a submachine which transits away from it.
- Fixes #734
> Move post state interceptor call later

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/StateConfigurer.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/action/ActionTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/action/ReactiveActionTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/configurers/DefaultStateConfigurerTests.java
- Add stateDoFunction, stateEntryFunction and stateExitFunction methods
taking Function with a state to register reactive actions.
- Don't yet to a full take on all similar action methods as we need
to think about how these should be named and what old methods to
depecate.
- Relates #743
> Add reactive state actions

- build.gradle
- spring-statemachine-core/src/main/java/org/springframework/statemachine/ensemble/DistributedStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/action/DistributedLeaderActionTests.java
- spring-statemachine-test/src/main/java/org/springframework/statemachine/test/StateMachineTestPlan.java
- spring-statemachine-test/src/test/java/org/springframework/statemachine/test/StateMachineTestingTests.java
- Move to use reactive methods and for now block
as concept is really blocking. Full reactive stuff
needs bigger overhaul.
- Fix event issues in DistributedStateMachine as these
caused issues when StateMachineTestPlan were changed to
send events via reactive methods.
- Relates #744
- Relates #750
> Reactive changes for StateMachineTestPlan

- spring-statemachine-core/src/main/java/org/springframework/statemachine/processor/StateMachineAnnotationPostProcessor.java
- As AnnotationUtils.getAnnotations from framework is deprecated
from 5.2 move over to MergedAnnotations api.
- Relates to #765
> Fix deprecation in StateMachineAnnotationPostProcessor

- spring-statemachine-build-tests/src/test/java/org/springframework/statemachine/buildtests/RedisPersistTests.java
- Fixing a simple type in an origin changes
which caused this test to fail.
- Relates #744
> Fix RedisPersistTests

- spring-statemachine-core/src/main/java/org/springframework/statemachine/service/DefaultStateMachineService.java
- Now starting machine outside of a sycn block with
acquire vs. release. This should allow long running
start in a machine to allow next acquire to work faster.
- Fixes #754
> Relax sync in DefaultStateMachineService

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitionBuilder.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/AbstractTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/TransitionData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/guard/Guards.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/guard/ReactiveGuard.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/JoinPseudoState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractExternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractInternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractLocalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/DefaultExternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/DefaultInternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/DefaultLocalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/Transition.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateContextExpressionMethodsTests.java
- spring-statemachine-data/src/main/java/org/springframework/statemachine/data/RepositoryStateMachineModelFactory.java
- spring-statemachine-uml/src/main/java/org/springframework/statemachine/uml/support/UmlModelParser.java
- First changes to introduce ReactiveGuard similar to work done
for ReactiveAction. User level interface is ReactiveGuard but internally
it is handled as its super type Function<StateContext<S, E>, Mono<Boolean>>.
- This change still keeps some calls as blocking which will get changed
in futher commits to get a full reactive chain.
- Touching only Transition to change guard signature, other use of blocking guard
internally need to get similar changes in next commits.
- Baby steps...
- Relates #791
> Initial reactive Guard changes

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/ReactiveStateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/InitialTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/Transition.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/EventDeferTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateContextExpressionMethodsTests.java
- For Guard and Transition change call stach to be fully
reactive from executor. Some changed signatures similarly
what was needed for reactive Actions.
- Disabling one smoke test to get figure out later as
something is broken somewhere, possible reactor bug...
- Relates #791
> Change things around guards to reactive

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/ReactiveStateMachineExecutor.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/EventDeferTests.java
- Re-enable test in EventDeferTests as this NPE fix
now handles smoke test.
- Relates #791
> Fix NPR in ReactiveStateMachineExecutor

- docs/src/reference/asciidoc/sm-config.adoc
- docs/src/reference/asciidoc/sm-persist.adoc
> Fix typo in documentation

- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ObjectState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/ReactiveStateMachineExecutor.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineErrorTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/TestUtils.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/security/AbstractSecurityTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/security/EventSecurityTests.java
- Before attempting to add better level of error handling,
discard all errors what might come from action execution.
- Handle some cases where event deny is reported back as accepted.
- Fix reactor error for double subcription.
- Relates #821
> Fix reactive event handling

- spring-statemachine-core/src/main/java/org/springframework/statemachine/StateMachineEventResult.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/StateMachineSystemConstants.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ObjectState.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/ReactiveStateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineExecutor.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineUtils.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineErrorTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/security/EventSecurityTests.java
- New concept of using callback to pass on error as
things can't be properly propagated as we're manually
dispatching to processor.
- Relates #821
> Pass error from executor

- spring-statemachine-core/src/main/java/org/springframework/statemachine/access/ReactiveStateMachineAccess.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/access/StateMachineAccess.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/StateMachineResetTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/access/StateMachineAccessTests.java
- Re-implement resetStateMachineReactively as fully reactive
chain by following same logic as in blocking version.
- New interface ReactiveStateMachineAccess as we need to
know if one need to call reactive method.
- Fixes #911
> Change machine reset to reactive

- docs/src/reference/asciidoc/appendix-reactormigration-communicating.adoc
- docs/src/reference/asciidoc/sm-triggers.adoc
- spring-statemachine-core/src/main/java/org/springframework/statemachine/ensemble/DistributedStateMachine.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/region/Region.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/ReactiveTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/access/StateMachineAccessTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsMigrationTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateContextExpressionMethodsTests.java
- spring-statemachine-zookeeper/src/test/java/org/springframework/statemachine/zookeeper/ZookeeperStateMachineEnsembleTests.java
- While this doesn't change underlying behaviour, add sendEventCollect
method which takes a mono and returns a mono as list of results.
- Add some notes to docs why this is like this, aka having regions
returns multiple results.
- Fixes #922
> Add api sugar for mono gets mono

- spring-statemachine-core/src/main/java/org/springframework/statemachine/support/ReactiveStateMachineExecutor.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/TestUtils.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/action/ReactiveAction2Tests.java
- Change flatMap to use concurrency 1 in a trigger handling which
should fix issues when events are sent fast.
- Fixes #942
> Limit trigger handling concurrency

- spring-statemachine-core/src/main/java/org/springframework/statemachine/service/DefaultStateMachineService.java
A persisted statemachine with orthogonal states will not be correctly
restored as only the top region gets correctly reset. Tests in
StateMachineResetTests use the correct way to reset the statemachine
with all regions
> Restore all regions of statemachine

- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/builders/StateMachineTransitionBuilder.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/AbstractTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultExternalTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultInternalTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/DefaultLocalTransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configurers/TransitionConfigurer.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/config/model/TransitionData.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractExternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractInternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractLocalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/AbstractTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/DefaultExternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/DefaultInternalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/DefaultLocalTransition.java
- spring-statemachine-core/src/main/java/org/springframework/statemachine/transition/Transition.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/config/model/StateMachineModelTests.java
- spring-statemachine-core/src/test/java/org/springframework/statemachine/support/StateContextExpressionMethodsTests.java
- spring-statemachine-uml/src/main/java/org/springframework/statemachine/uml/support/UmlModelParser.java
Given two instances of a `StateMachine<S, E>` resulting from the same `StateMachineFactory<S, E>` and a `StateMachineListener<S, E>`, I can listen for state changes and uniquely identify the state by its id, regardless of the state machine instance:
@Override
stateEntered(State<S, E> state) {
S id = state.getId();
// "state" is a different object depending on the state machine instance
// "id" is the same in different state machine instances
}
For transitions, this is not possible:
@Override
public void transition(Transition<S, E> transition) {
// "transition" is a different object depending on the state machine instance
// there is no "id" available
}
In the current implementation I did not find a way to uniquely identify the `Transition` across `StateMachine` instances. In UML, …
> Implement named transitions (fix #850)

- .github/workflows/ci-boot.yml
- .github/workflows/ci.yml
- .github/workflows/release-ga.yml
- .github/workflows/release-milestone.yml
- README.adoc
- settings.gradle
This pull request connects the build to the Gradle Enterprise instance at https://ge.spring.io/. This allows the Spring Statemachine project to benefit from deep build insights provided by build scans and faster build speeds for all contributors as a result of remote build caching. 
This Gradle Enterprise instance has all features and extensions enabled and is freely available for use by Spring Statemachine and all other Spring projects. On this Gradle Enterprise instance, Spring Statemachine will have access not only to all of the published build scans, but other aggregate data features such as:
- Dashboards to view all historical build scans, along with performance trends over time
- Build failure analytics for enhanced investigation and diagnosis of build failures
- Test failure …
> Connect build to ge.spring.io to benefit from deep build insights and faster builds

- buildSrc/build.gradle
- docs/src/reference/asciidoc/getting-started.adoc
- gradle.properties
- [com.gradle.enterprise](https://plugins.gradle.org/plugin/com.gradle.enterprise) from 3.14.1 to 3.16.2
- [io.spring.ge.conventions](https://github.com/spring-io/gradle-enterprise-conventions) from 0.0.14 to 0.0.15
Based on commits in spring-framework repo, internally spring team should support latest Gradle Enterprise plugin:
- Commit with note that only 3.15 version is supported: spring-projects/spring-framework@e3f185a696b0d6ca017a83366f24ed692573d14e 
- Commit with 3.16 version: spring-projects/spring-framework@b7e4fa16cae5f5a45fd661c51d558c8b9e5c39ae
> Upgrade com.gradle.enterprise plugin to 3.16.2

- CONTRIBUTING.md
@pivotal-cla This is an Obvious Fix
> Refer to main branch instead of master
